-- 1. Create Builders / Creators table
create table if not exists public.builders (
    id bigint generated by default as identity primary key,
    name text not null,
    email text unique,
    organization text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Groups & Environments table (e.g., Production-US, Staging-Internal)
create table if not exists public.environments (
    id bigint generated by default as identity primary key,
    name text not null unique, -- e.g., 'production', 'staging', 'development'
    group_name text not null,  -- e.g., 'core-infra', 'erp-backend', 'analytics'
    description text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enhanced Packages / Repositories table
create table if not exists public.packages (
    id bigint generated by default as identity primary key,
    name text not null unique,
    title text not null,
    "desc" text,
    version text not null,
    repo text not null,
    work_dir text not null,
    builder_id bigint references public.builders(id) on delete set null,
    
    -- Target Platform & Architecture Mappings
    supported_os text[] default '{}',   -- e.g., {'linux', 'windows', 'darwin'}
    supported_arch text[] default '{}', -- e.g., {'amd64', 'arm64', '386'}
    
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enhanced Services table mapped to packages, environments, and runtimes
create table if not exists public.services (
    id bigint generated by default as identity primary key,
    name text not null unique,
    title text not null,
    "desc" text,
    tags text[] default '{}',
    port int not null,
    
    -- Foreign keys & Mapping
    package_id bigint references public.packages(id) on delete cascade,
    environment_id bigint references public.environments(id) on delete set null,
    
    -- Execution Runtime (user, server, docker, podman, vm)
    runtime_type text not null check (runtime_type in ('user', 'server', 'docker', 'podman', 'vm')),
    runtime_config jsonb default '{}'::jsonb, -- Store specific runtime options (e.g., container image, VM memory specs)
    
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.builders enable row level security;
alter table public.environments enable row level security;
alter table public.packages enable row level security;
alter table public.services enable row level security;

-- Public Read Policies
create policy "Allow public read access on builders" on public.builders for select using (true);
create policy "Allow public read access on environments" on public.environments for select using (true);
create policy "Allow public read access on packages" on public.packages for select using (true);
create policy "Allow public read access on services" on public.services for select using (true);