// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckServiceVersion(arg1) {
  return window['go']['main']['App']['CheckServiceVersion'](arg1);
}

export function GetServiceList() {
  return window['go']['main']['App']['GetServiceList']();
}

export function ServiceAction(arg1, arg2) {
  return window['go']['main']['App']['ServiceAction'](arg1, arg2);
}
