// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {srvc} from '../models';

export function CheckServiceVersion(arg1:string):Promise<srvc.VersionCheckResult>;

export function GetServiceList():Promise<Array<srvc.Services>>;

export function ServiceAction(arg1:string,arg2:string):Promise<void>;
